services:
  - type: web
    name: anbu-printing-press
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && npm run postinstall && node build-client.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PUPPETEER_CACHE_DIR
        value: /tmp/puppeteer-cache
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
