services:
  - type: web
    name: anbu-printing-press
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && node build-client.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
