services:
  - type: web
    name: anbu-printing-press
    env: node
    buildCommand: cd server && npm install && chmod +x render-build.sh && ./render-build.sh
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
